### ISSUE TITLE
What is @NpmPackage needed for

### ISSUE THREAD

**Issue by andersforsell** [Artur-/flow-lit#1]
Hi,

I'm evaluating the Vaadin 14 beta and looking at your example I'm wondering what the NpmPackage annotation is good for?

**Comment by Artur-** [comment]
The `NpmPackage` annotation makes sure that the given npm dependency is included in the project. It is exactly the same as adding the npm package to `package.json` using e.g. `npm install --save lit-element`.

The latest commit actually removes that annotation as it uses a Flow version with `LitTemplate` support (supports model and `@Id` mapping) and that one automatically includes the needed npnm package
